version: 2
jobs:
  ruby-2.4:
    docker:
      - image: circleci/ruby:2.4.4
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=2.0.1' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler:2.0.1
      - run: bundle
      - run: rake test
  ruby-2.5:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=2.0.1' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler:2.0.1
      - run: bundle
      - run: rake test
  ruby-2.6:
    docker:
      - image: circleci/ruby:2.6.6
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=2.0.1' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler:2.0.1
      - run: bundle
      - run: rake test
workflows:
  version: 2
  rubies:
    jobs:
      - ruby-2.4
      - ruby-2.5
      - ruby-2.6
